# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'login.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QSize(1297, 737))
        self.imagem = QLabel(Form)
        self.imagem.setObjectName(u"imagem")
        self.imagem.setEnabled(True)
        self.imagem.setGeometry(QRect(0, 0, 1297, 737))
        sizePolicy.setHeightForWidth(self.imagem.sizePolicy().hasHeightForWidth())
        self.imagem.setSizePolicy(sizePolicy)
        self.imagem.setMaximumSize(QSize(1297, 737))
        self.imagem.setTextFormat(Qt.PlainText)
        self.imagem.setPixmap(QPixmap(u"images_.qrc/fundorea.png"))
        self.imagem.setScaledContents(True)
        self.imagem.setAlignment(Qt.AlignCenter)
        self.faixa = QLabel(Form)
        self.faixa.setObjectName(u"faixa")
        self.faixa.setEnabled(True)
        self.faixa.setGeometry(QRect(160, 0, 470, 737))
        self.faixa.setMaximumSize(QSize(470, 737))
        self.faixa.setPixmap(QPixmap(u"images_.qrc/fundofaixa.png"))
        self.faixa.setScaledContents(True)
        self.saudacao = QLabel(Form)
        self.saudacao.setObjectName(u"saudacao")
        self.saudacao.setGeometry(QRect(310, 80, 181, 111))
        font = QFont()
        font.setFamily(u"Biko")
        font.setPointSize(60)
        self.saudacao.setFont(font)
        self.informe = QLabel(Form)
        self.informe.setObjectName(u"informe")
        self.informe.setGeometry(QRect(190, 190, 401, 21))
        font1 = QFont()
        font1.setFamily(u"Biko")
        font1.setPointSize(14)
        self.informe.setFont(font1)
        self.txt_nome = QLineEdit(Form)
        self.txt_nome.setObjectName(u"txt_nome")
        self.txt_nome.setEnabled(True)
        self.txt_nome.setGeometry(QRect(210, 270, 371, 51))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.txt_nome.setPalette(palette)
        self.txt_nome.setFont(font1)
        self.txt_nome.setStyleSheet(u"")
        self.txt_senha = QLineEdit(Form)
        self.txt_senha.setObjectName(u"txt_senha")
        self.txt_senha.setEnabled(True)
        self.txt_senha.setGeometry(QRect(210, 370, 371, 51))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.txt_senha.setPalette(palette1)
        self.txt_senha.setFont(font1)
        self.txt_senha.setEchoMode(QLineEdit.Password)
        self.nome = QLabel(Form)
        self.nome.setObjectName(u"nome")
        self.nome.setGeometry(QRect(210, 246, 251, 20))
        self.nome.setFont(font1)
        self.senha = QLabel(Form)
        self.senha.setObjectName(u"senha")
        self.senha.setGeometry(QRect(210, 346, 171, 20))
        self.senha.setFont(font1)
        self.btn_login = QPushButton(Form)
        self.btn_login.setObjectName(u"btn_login")
        self.btn_login.setGeometry(QRect(320, 450, 141, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        brush3 = QBrush(QColor(120, 120, 120, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.btn_login.setPalette(palette2)
        self.btn_login.setFont(font1)
        self.informe_2 = QLabel(Form)
        self.informe_2.setObjectName(u"informe_2")
        self.informe_2.setGeometry(QRect(200, 596, 191, 20))
        self.informe_2.setFont(font1)
        self.informe_3 = QLabel(Form)
        self.informe_3.setObjectName(u"informe_3")
        self.informe_3.setGeometry(QRect(200, 620, 371, 31))
        self.informe_3.setFont(font1)
        self.btn_cadastro = QPushButton(Form)
        self.btn_cadastro.setObjectName(u"btn_cadastro")
        self.btn_cadastro.setGeometry(QRect(300, 670, 181, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.btn_cadastro.setPalette(palette3)
        self.btn_cadastro.setFont(font1)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.imagem.setText("")
        self.faixa.setText("")
        self.saudacao.setText(QCoreApplication.translate("Form", u"Ol\u00e1!", None))
        self.informe.setText(QCoreApplication.translate("Form", u"Irforme seus dados para iniciar a sess\u00e3o:", None))
        self.nome.setText(QCoreApplication.translate("Form", u"Primeiro Nome:", None))
        self.senha.setText(QCoreApplication.translate("Form", u"Senha:", None))
        self.btn_login.setText(QCoreApplication.translate("Form", u"Login", None))
        self.informe_2.setText(QCoreApplication.translate("Form", u"N\u00e3o \u00e9 cadastrado?", None))
        self.informe_3.setText(QCoreApplication.translate("Form", u"Clique aqui para o primeiro acesso:", None))
        self.btn_cadastro.setText(QCoreApplication.translate("Form", u"Cadastre-se", None))
    # retranslateUi

